name: Terraform Destroy Pipeline

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main
      - production
    paths:
      - 'terraform/**'  # Only trigger when Terraform files change
  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  terraform-destroy:
    if: github.event_name == 'workflow_dispatch' || (github.event_name == 'pull_request' && github.event.action == 'closed') || (github.ref == 'refs/heads/production' && github.event_name == 'push')
    name: Terraform Destroy
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.5.7
          terraform_wrapper: false

      - name: Terraform Init
        run: terraform init -backend-config="bucket=your-tf-state-bucket" -backend-config="key=terraform.tfstate" -backend-config="region=us-east-1"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          TF_VAR_environment: production
